import About  from "@/containers/about";

export const metadata = {
    title: "Prettyfolio - About Us",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <About />
  )
}
