import { Source_Sans_3 } from "next/font/google";
import 'swiper/css/pagination';
//import 'bootstrap/dist/css/bootstrap.min.css';
import "/sass/bootstrap.scss";
import 'animate.css';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';

const source = Source_Sans_3({ subsets: ["latin"] });

export const metadata = {
  title: "Prettyfolio - Portfolio Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={source.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
