import Blog from '@/containers/blog';

export const metadata = {
    title: "Prettyfolio - Blog",
    description: "Generated by create next app",
};

export default function page() {
  return (
    <Blog />
  )
}
